version: "3"

services:
  wagglechat:
    build: .
    ports:
      - 80:80
    networks:
      - waggle
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - chatdb:/data/db
    networks:
      - waggle
    restart: on-failure

networks:
  waggle: {}

volumes:
  chatdb: